import _aio from './lib/aio.js';
import _berita from './lib/berita.js';
import _bratMaker from './lib/bratMaker.js';
import _clipCafeSearch from './lib/clipCafeSearch.js';
import _deepai from './lib/deepai.js';
import _facebookDownloader from './lib/facebookDownloader.js';
import _findThatMeme from './lib/findThatMeme.js';
import _gdrive from './lib/gdrive.js';
import _gita from './lib/gita.js';
import _gitagram from './lib/gitagram.js';
import _githubStalk from './lib/githubStalk.js';
import _googleNews from './lib/googleNews.js';
import _imageHD from './lib/imageHD.js';
import _imageUpscale from './lib/imageUpscale.js';
import _pinterestSearch from './lib/pinterestSearch.js';
import _spotifyDownload from './lib/spotifyDownload.js';
import _spotifySearch from './lib/spotifySearch.js';
import _tiktokStalk from './lib/tiktokStalk.js';
import _twitterDownloader from './lib/twitterDownloader.js';
import _twitterStalk from './lib/twitterStalk.js';
import _watchpeakPerson from './lib/watchpeakPerson.js';
import _watchpeakTitle from './lib/watchpeakTitle.js';
import _web2apk from './lib/web2apk.js';
import _ytmp3 from './lib/ytmp3.js';
import _ytmp4 from './lib/ytmp4.js';
import { withLogging } from './utils/logWrapper.js';
import { withConcurrencyLimit, setConcurrencyLimit, getConcurrencyLimit } from './utils/concurrencyLimiter.js';
import { setHttpConfig, getHttpConfig } from './utils/httpClient.js';
import { setApiKey, getApiKey } from './utils/apiKeyStore.js';
import { setDebug } from './utils/logger.js';
import { checkForUpdates, selfUpdate } from './utils/selfUpdate.js';
import { makeCaseInsensitive } from './utils/caseInsensitiveProxy.js';

const aio = withLogging('aio', withConcurrencyLimit(_aio));
const berita = withLogging('berita', withConcurrencyLimit(_berita));
const bratMaker = withLogging('bratMaker', withConcurrencyLimit(_bratMaker));
const clipCafeSearch = withLogging('clipCafeSearch', withConcurrencyLimit(_clipCafeSearch));
const deepai = withLogging('deepai', withConcurrencyLimit(_deepai));
const facebookDownloader = withLogging('facebookDownloader', withConcurrencyLimit(_facebookDownloader));
const findThatMeme = withLogging('findThatMeme', withConcurrencyLimit(_findThatMeme));
const gdrive = withLogging('gdrive', withConcurrencyLimit(_gdrive));
const gita = withLogging('gita', withConcurrencyLimit(_gita));
const gitagram = withLogging('gitagram', withConcurrencyLimit(_gitagram));
const githubStalk = withLogging('githubStalk', withConcurrencyLimit(_githubStalk));
const googleNews = withLogging('googleNews', withConcurrencyLimit(_googleNews));
const imageHD = withLogging('imageHD', withConcurrencyLimit(_imageHD));
const imageUpscale = withLogging('imageUpscale', withConcurrencyLimit(_imageUpscale));
const pinterestSearch = withLogging('pinterestSearch', withConcurrencyLimit(_pinterestSearch));
const spotifyDownload = withLogging('spotifyDownload', withConcurrencyLimit(_spotifyDownload));
const spotifySearch = withLogging('spotifySearch', withConcurrencyLimit(_spotifySearch));
const tiktokStalk = withLogging('tiktokStalk', withConcurrencyLimit(_tiktokStalk));
const twitterDownloader = withLogging('twitterDownloader', withConcurrencyLimit(_twitterDownloader));
const twitterStalk = withLogging('twitterStalk', withConcurrencyLimit(_twitterStalk));
const watchpeakPerson = withLogging('watchpeakPerson', withConcurrencyLimit(_watchpeakPerson));
const watchpeakTitle = withLogging('watchpeakTitle', withConcurrencyLimit(_watchpeakTitle));
const web2apk = withLogging('web2apk', withConcurrencyLimit(_web2apk));
const ytmp3 = withLogging('ytmp3', withConcurrencyLimit(_ytmp3));
const ytmp4 = withLogging('ytmp4', withConcurrencyLimit(_ytmp4));

export { aio, berita, bratMaker, clipCafeSearch, deepai, facebookDownloader, findThatMeme, gdrive, gita, gitagram, githubStalk, googleNews, imageHD, imageUpscale, pinterestSearch, spotifyDownload, spotifySearch, tiktokStalk, twitterDownloader, twitterStalk, watchpeakPerson, watchpeakTitle, web2apk, ytmp3, ytmp4, setHttpConfig, getHttpConfig, setApiKey, getApiKey, setDebug, setConcurrencyLimit, getConcurrencyLimit, checkForUpdates, selfUpdate };
const _all = { aio, berita, bratMaker, clipCafeSearch, deepai, facebookDownloader, findThatMeme, gdrive, gita, gitagram, githubStalk, googleNews, imageHD, imageUpscale, pinterestSearch, spotifyDownload, spotifySearch, tiktokStalk, twitterDownloader, twitterStalk, watchpeakPerson, watchpeakTitle, web2apk, ytmp3, ytmp4, setHttpConfig, getHttpConfig, setApiKey, getApiKey, setDebug, setConcurrencyLimit, getConcurrencyLimit, checkForUpdates, selfUpdate };
export default makeCaseInsensitive(_all);
